### ISSUE TITLE
mixins.scss

### ISSUE THREAD

**Issue by benenright** [torchbox/design-in-browser-bootstrap#11]
Add bank of useful mixins as a starting point.

Thinks like, transitions, gradients, border radius...

**Comment by davecranwell** [comment]
These were present in the LESS version from the start, but didn't seem to get used. This may just be a training issue.

**Comment by davecranwell** [comment]
The Gulp task to compile SASS now includes auto-prefixing where necessary: https://github.com/torchbox/design-in-browser-bootstrap/blob/master/gulpfile.js/tasks/sass.js#L10

In lay-terms, this means you can write your CSS without any prefixes, as if browser prefixing wasn't necessary at all, and gulp will do the prefixing for you.

Since most of our previous mixins were merely to provide prefixing, the need for a library of mixins is greatly reduced.
