### ISSUE TITLE
Change structure of CSS folder

### ISSUE THREAD

**Issue by benenright** [torchbox/design-in-browser-bootstrap#7]
We would prefer no sub-folders. So just have:

CSS >
 main.scss
 mixins.scss
 variables.scss
 layout.scss

I think we all use a different selection of these, so main thing is no sub-folders I guess. (e.g I'd add a components.scss but James just uses main.scss).

Would there be a gridle.scss that would go in here, in place of say layout.scss ? We'd be happy with that.

As for normalise.scss, I dislike that it adds values for margins e.g. 40px, do you know any more vanilla ones?). Not a disaster if we stick with Normalise, will take your lead - but maybe you could just zero a few values?

Cheers.

**Comment by davecranwell** [comment]
Normalize is the other-dimensional twin of Reset. 

Reset removes everything - this frustratingly means you have to add lots of basic stuff back in. 

Normalize gives everything a common default value, consistent with a browser's native default styles, but ensures consistency between browsers - this means you occasionally have to tweak something, but you can mostly get going quickly. 

We generally want to reduce our work load so I thing normalize is our best bet for now.

**Comment by davecranwell** [comment]
The "css" folder is now called "scss" since it contains no vanilla css files. The addition of gridle, comprised of 8 files, means having no structure to the css/sass directory would be confusing, particularly as you're never meant to edit the contents of gridle's internal files. Gridle _and_ normalize have therefore now been put into a "vendor" folder as is standard industry practice.

I have however removed the components folder, leaving just 4 core files in the root of the "scss" directory.
