### ISSUE TITLE
jquery link

### ISSUE THREAD

**Issue by benenright** [torchbox/design-in-browser-bootstrap#8]
Should we link to this remotely rather than hosting to ensure it's always the most recent version?

**Comment by davecranwell** [comment]
The most recent version doesn't support IE8, which may still be required in some cases. Having said that, I don't see a reason not to update it, provided that designers are aware of any impact it may have on their own browser testing.

**Comment by davecranwell** [comment]
Using remote links to jQuery is a nice idea however no remote hosting CDNs provide a link directly to "the latest" version, since that version could change from one page load to the next, with unpredictable effects.

An alternative might be to add Bower to automatically download the latest jQuery, but that adds quite a lot of cruft to the repo.

Also I don't know how reliable your internet is, but waiting for jQuery to load at times of poor internet is really interruptive to one's "flow"!

For now I've updated the version of jQuery provided.
